apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: otanodes.ota.theriseunion.io
  labels:
    app.kubernetes.io/name: edge-ota
    app.kubernetes.io/part-of: edge-ota
spec:
  group: ota.theriseunion.io
  names:
    kind: OTANode
    listKind: OTANodeList
    plural: otanodes
    singular: otanode
    shortNames:
      - node
      - onode
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: IP
          type: string
          jsonPath: .status.ipAddress
        - name: LastSeen
          type: date
          jsonPath: .status.lastHeartbeat
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - deviceId
              properties:
                deviceId:
                  type: string
                  description: Unique device identifier
                labels:
                  type: object
                  additionalProperties:
                    type: string
                  description: Custom labels for the device
                annotations:
                  type: object
                  additionalProperties:
                    type: string
                  description: Custom annotations
                tempStoragePath:
                  type: string
                  description: Path for temporary file storage
                auth:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    token:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Online
                    - Offline
                    - Unknown
                ipAddress:
                  type: string
                hostname:
                  type: string
                osInfo:
                  type: string
                lastHeartbeat:
                  type: string
                  format: date-time
                registeredAt:
                  type: string
                  format: date-time
                natsSubject:
                  type: string
                tempStoragePath:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
