apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: apiserver-project
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: apiserver-project
  name: webhook-server-cert
  namespace: edge-system
spec:
  dnsNames:
  - {{ include "edge-controller.fullname" . }}.edge-system.svc
  - {{ include "edge-controller.fullname" . }}.edge-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: edge-selfsigned-issuer
  secretName: webhook-server-cert