# Dockerfile.museum - Package all charts into ChartMuseum image
FROM ghcr.io/helm/chartmuseum:v0.16.3

# Copy all packaged charts to chartmuseum storage
COPY bin/_output/*.tgz /charts/

# ChartMuseum will serve charts from /charts directory
ENTRYPOINT ["/chartmuseum"]
CMD ["--storage", "local", \
     "--storage-local-rootdir", "/charts", \
     "--port", "8080"]
