#!/usr/bin/env python3
"""
Generate combined recording rules from modular PrometheusRule files

This script combines individual PrometheusRule files from the rules/ directory
into a single recording-rules-combined.yaml file suitable for ConfigMap usage.

The script preserves YAML literal blocks for better readability and maintains
proper formatting without escaped newlines.
"""

import yaml
import os
from pathlib import Path

# Define rule file priority order
RULE_FILES = [
    # P1 - Foundation metrics (node, GPU)
    "node-recording-rules.yaml",
    "gpu-recording-rules.yaml",
    # P2 - Aggregated metrics (nodegroup, cluster, workspace, namespace)
    "nodegroup-recording-rules.yaml",
    "cluster-recording-rules.yaml",
    "workspace-recording-rules.yaml",
    "namespace-recording-rules.yaml",
    # NPU metrics
    "npu-recording-rules.yaml",
]

def load_prometheus_rule(file_path):
    """Load a PrometheusRule file and extract its groups"""
    with open(file_path, 'r') as f:
        rule = yaml.safe_load(f)

    if 'spec' not in rule or 'groups' not in rule['spec']:
        raise ValueError(f"Invalid PrometheusRule format in {file_path}")

    return rule['spec']['groups']

def generate_combined_rules(rules_dir, output_file):
    """Generate combined recording rules from modular files"""
    all_groups = []

    print(f"Combining recording rules from {rules_dir}/")

    for rule_file in RULE_FILES:
        file_path = rules_dir / rule_file
        if not file_path.exists():
            print(f"  ⚠️  Skipping missing file: {rule_file}")
            continue

        print(f"  ✅ Processing: {rule_file}")
        groups = load_prometheus_rule(file_path)
        all_groups.extend(groups)
        print(f"     Added {len(groups)} rule group(s)")

    # Create combined structure
    combined = {'groups': all_groups}

    # Write with proper YAML formatting
    with open(output_file, 'w') as f:
        # Write header comment
        f.write("# ========================================================================\n")
        f.write("# Combined Prometheus Recording Rules\n")
        f.write("# Auto-generated from modular PrometheusRule files\n")
        f.write("#\n")
        f.write("# DO NOT EDIT THIS FILE DIRECTLY!\n")
        f.write("# Edit individual files in rules/ directory and regenerate using:\n")
        f.write("#   python3 generate-combined-rules.py\n")
        f.write("#\n")
        f.write("# Source files (in priority order):\n")
        for rule_file in RULE_FILES:
            f.write(f"# - {rule_file}\n")
        f.write("# ========================================================================\n\n")

        # Write YAML with proper formatting
        yaml.dump(combined, f,
                  default_flow_style=False,
                  allow_unicode=True,
                  sort_keys=False,
                  width=80,
                  indent=2)

    print(f"\n✅ Generated: {output_file}")
    print(f"   Total groups: {len(all_groups)}")

if __name__ == '__main__':
    script_dir = Path(__file__).parent
    rules_dir = script_dir / 'rules'
    output_file = script_dir / 'recording-rules-combined.yaml'

    generate_combined_rules(rules_dir, output_file)
