apiVersion: v1
kind: Service
metadata:
  name: edge-grafana-nodeport
  namespace: observability-system
  labels:
    app: edge-grafana
    component: grafana
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort: 30300  # 可选：指定固定的 NodePort（范围 30000-32767）
    protocol: TCP
    name: web
  selector:
    app: edge-grafana
