apiVersion: iam.theriseunion.io/v1alpha1
kind: ReverseProxy
metadata:
  name: grafana-proxy
  namespace: observability-system
  labels:
    app: edge-grafana
    component: reverse-proxy
spec:
  matcher:
    method: '*'
    path: /oapis/grafana.theriseunion.io/v1/*
  upstream:
    host: 116.63.161.198
    port: 30010
    scheme: http
  directives:
    rewrite:
      - from: '^/oapis/grafana\.theriseunion\.io/v1/(.*)$'
        to: '/$1'
