{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-logs.fullname" . }}-clickhouse-init
  namespace: {{ include "edge-logs.namespace" . }}
  labels:
    {{- include "edge-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
data:
  users.xml: |
    <clickhouse>
      <users>
        <default>
          <password></password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
          <access_management>1</access_management>
        </default>
      </users>
    </clickhouse>
  01_tables.sql: |
    -- ClickHouse schema for edge-logs
    CREATE DATABASE IF NOT EXISTS edge_logs;
    USE edge_logs;

    -- Main logs table
    CREATE TABLE IF NOT EXISTS logs (
        timestamp          DateTime64(9) CODEC(Delta(8), ZSTD(1)),
        dataset            LowCardinality(String) CODEC(ZSTD(1)),
        content            String CODEC(ZSTD(1)),
        severity           LowCardinality(String) CODEC(ZSTD(1)),
        container_id       String CODEC(ZSTD(1)),
        container_name     LowCardinality(String) CODEC(ZSTD(1)),
        pid                String CODEC(ZSTD(1)),
        host_ip            LowCardinality(String) CODEC(ZSTD(1)),
        host_name          LowCardinality(String) CODEC(ZSTD(1)),
        k8s_namespace_name LowCardinality(String) CODEC(ZSTD(1)),
        k8s_pod_name       LowCardinality(String) CODEC(ZSTD(1)),
        k8s_pod_uid        String CODEC(ZSTD(1)),
        k8s_node_name      LowCardinality(String) CODEC(ZSTD(1)),
        tags               Map(String, String) CODEC(ZSTD(1)),
        INDEX idx_content content TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 1,
        INDEX idx_tags tags TYPE bloom_filter GRANULARITY 1
    )
    ENGINE = MergeTree()
    PARTITION BY (dataset, toDate(timestamp))
    ORDER BY (dataset, host_ip, timestamp)
    TTL toDateTime(timestamp) + INTERVAL {{ .Values.clickhouse.config.retention_days }} DAY DELETE
    SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

    -- Datasets table
    CREATE TABLE IF NOT EXISTS datasets (
        name String,
        display_name String,
        description String,
        created_at DateTime DEFAULT now(),
        updated_at DateTime DEFAULT now(),
        retention_days UInt32 DEFAULT {{ .Values.clickhouse.config.retention_days }},
        is_active UInt8 DEFAULT 1
    )
    ENGINE = ReplacingMergeTree(updated_at)
    ORDER BY (name);

    -- Insert default dataset
    INSERT INTO datasets (name, display_name, description) VALUES
    ('default', 'Default Dataset', 'Default dataset for edge logs')
    ON DUPLICATE KEY UPDATE updated_at = now();

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-logs.clickhouse.serviceName" . }}
  namespace: {{ include "edge-logs.namespace" . }}
  labels:
    {{- include "edge-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - name: http
      port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: tcp
      port: {{ .Values.clickhouse.service.tcpPort }}
      targetPort: tcp
      protocol: TCP
  selector:
    {{- include "edge-logs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edge-logs.fullname" . }}-clickhouse
  namespace: {{ include "edge-logs.namespace" . }}
  labels:
    {{- include "edge-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  serviceName: {{ include "edge-logs.clickhouse.serviceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "edge-logs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clickhouse
  template:
    metadata:
      labels:
        {{- include "edge-logs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: clickhouse
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: clickhouse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "edge-logs.clickhouse.image" . }}
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.clickhouse.service.httpPort }}
              protocol: TCP
            - name: tcp
              containerPort: {{ .Values.clickhouse.service.tcpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: users-config
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "edge-logs.fullname" . }}-clickhouse-init
        - name: users-config
          configMap:
            name: {{ include "edge-logs.fullname" . }}-clickhouse-init
            items:
              - key: users.xml
                path: users.xml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.clickhouse.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "edge-logs.labels" . | nindent 10 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.clickhouse.persistence.storageClass }}
        {{- if (eq "-" .Values.clickhouse.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.clickhouse.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.clickhouse.persistence.size | quote }}
  {{- else }}
        - name: data
          emptyDir: {}
  {{- end }}
{{- end }}