---
# iLogtail DaemonSet for log collection
# Sends logs to OTEL Collector via OTLP gRPC (ADR-001)
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-config
  namespace: {{ include "edge-logs.namespace" . }}
data:
  # iLogtail configuration for OTLP output
  user_yaml_config.d: |
    enable: true
    inputs:
      - Type: input_file
        FilePaths:
          - /var/log/containers/*.log
        ExcludeFiles:
          - ilogtail.*\.log
          - otel-collector.*\.log
    processors:
      # Parse JSON log content
      - Type: processor_json
        SourceKey: content
        KeepSource: false
        ExpandDepth: 1
        ExpandConnector: ""
        KeepSourceIfParseError: true
      # Extract log message from parsed JSON
      - Type: processor_rename
        SourceKeys: ["log"]
        DestKeys: ["content"]
        KeepSourceIfNotExist: true
      # Add K8s metadata as resource attributes
      - Type: processor_add_fields
        Fields:
          service.name: "edge-logs"
    flushers:
      # OTLP gRPC output to OTEL Collector
      - Type: flusher_otlp
        Logs:
          Endpoint: "otel-collector.{{ include "edge-logs.namespace" . }}.svc.cluster.local:4317"
          Timeout: 10000
          WaitForReady: true
          # Resource attributes mapping
          ResourceAttributes:
            - From: "__host_name__"
              Key: "host.name"
            - From: "__host_ip__"
              Key: "host.ip"
            - From: "_node_name_"
              Key: "k8s.node.name"
            - From: "_namespace_"
              Key: "k8s.namespace.name"
            - From: "_pod_name_"
              Key: "k8s.pod.name"
            - From: "_pod_uid_"
              Key: "k8s.pod.uid"
            - From: "_container_name_"
              Key: "k8s.container.name"
            - From: "_container_id_"
              Key: "container.id"
        Retry:
          MaxCount: 5
          InitialDelay: 1000
          MaxDelay: 30000

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ilogtail
  namespace: {{ include "edge-logs.namespace" . }}
  labels:
    app: ilogtail
    component: log-collector
spec:
  selector:
    matchLabels:
      app: ilogtail
  template:
    metadata:
      labels:
        app: ilogtail
        component: log-collector
    spec:
      serviceAccountName: {{ include "edge-logs.serviceAccountName" . }}
      automountServiceAccountToken: false
      containers:
        - name: ilogtail
          image: {{ include "edge-logs.ilogtail.image" . }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ALIYUN_LOG_ENV_TAGS
              value: ""
            - name: LOG_DATASET
              valueFrom:
                configMapKeyRef:
                  name: ilogtail-env
                  key: dataset
                  optional: true
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /usr/local/ilogtail/config/local/user_config.yaml
              subPath: user_yaml_config.d
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: run
              mountPath: /run
              readOnly: true
            - name: checkpoint
              mountPath: /usr/local/ilogtail/checkpoint
      volumes:
        - name: config
          configMap:
            name: ilogtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: run
          hostPath:
            path: /run
        - name: checkpoint
          hostPath:
            path: /var/lib/ilogtail-checkpoint
            type: DirectoryOrCreate
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux

---
# Environment configuration for iLogtail
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-env
  namespace: {{ include "edge-logs.namespace" . }}
data:
  dataset: "default"
