apiVersion: v1
kind: Secret
metadata:
  name: cloudcore
  namespace: {{ include "kubeedge.namespace" . }}
  labels:
    {{- include "kubeedge.cloudcore.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ ( include "kubeedge.genCloudCoreCerts" . ) | indent 2 }}
