apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apiserver-project
  name: edge-controller-manager
  namespace: edge-system
