# NodeGroup-Scoped RoleTemplates
# These RoleTemplates define permissions for nodegroup-scoped operations
# They aggregate into nodegroup-admin and nodegroup-viewer roles via label matching

# =============================================================================
# Category: nodegroup-node-management
# Purpose: Manage and view nodes within the nodegroup
# =============================================================================

apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-view-nodes
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点查看"
    theriseunion.io/description: "查看节点组中的所有节点及节点资源"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-node-management
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
spec:
  uiPermissions:
    - nodegroup/nodes.view
  rules:
  # Core node resources - read-only
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/status
    verbs:
    - get
    - list
    - watch
  # Node-related resources
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - pods/status
    verbs:
    - get
    - list
    - watch
  # Metrics and monitoring
  - apiGroups:
    - metrics.k8s.io
    resources:
    - nodes
    - pods
    verbs:
    - get
    - list
  # Storage related to nodes
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
  # Edge node viewing
  - apiGroups:
    - edge.theriseunion.io
    - devices.kubeedge.io
    resources:
    - edgenodes
    - devices
    - devicemodels
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-manage-nodes
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点管理"
    theriseunion.io/description: "创建、编辑和删除节点组中的节点"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-node-management
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-nodes"
spec:
  uiPermissions:
    - nodegroup/nodes.manage
  rules:
  # Core node resources - full management
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/status
    - nodes/proxy
    verbs:
    - '*'
  # Node-related resources
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - pods/status
    verbs:
    - get
    - list
    - watch
  # Metrics and monitoring
  - apiGroups:
    - metrics.k8s.io
    resources:
    - nodes
    - pods
    verbs:
    - get
    - list
  # Storage related to nodes
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
  # Edge node management
  - apiGroups:
    - edge.theriseunion.io
    - devices.kubeedge.io
    resources:
    - edgenodes
    - devices
    - devicemodels
    verbs:
    - '*'

# =============================================================================
# Category: nodegroup-access-control
# Purpose: Manage members and roles within the nodegroup
# =============================================================================

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-view-roles
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色查看"
    theriseunion.io/description: "查看节点组中的角色"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
spec:
  uiPermissions:
    - nodegroup/roles.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - iamroles
    - roletemplates
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-manage-roles
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色管理"
    theriseunion.io/description: "创建、编辑和删除节点组中的角色"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-roles"
spec:
  uiPermissions:
    - nodegroup/roles.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - iamroles
    - roletemplates
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-view-members
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员查看"
    theriseunion.io/description: "查看节点组中的成员"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-roles"
spec:
  uiPermissions:
    - nodegroup/members.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - nodegroupmembers
    - iamrolebindings
    - users
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-manage-members
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员管理"
    theriseunion.io/description: "邀请、移除和管理节点组中的成员"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-members"
spec:
  uiPermissions:
    - nodegroup/members.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - nodegroupmembers
    - iamrolebindings
    verbs:
    - '*'

# =============================================================================
# Category: nodegroup-settings
# Purpose: Manage and view nodegroup settings and configuration
# =============================================================================
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-view-settings
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点组设置查看"
    theriseunion.io/description: "查看节点组设置及配额"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-settings
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
spec:
  uiPermissions:
    - nodegroup/settings.view
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - nodegroups
    - nodegroups/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - resourcequotas
    - limitranges
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-manage-settings
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点组设置管理"
    theriseunion.io/description: "编辑节点组设置及配额"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-settings
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-settings"
spec:
  uiPermissions:
    - nodegroup/settings.manage
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - nodegroups
    - nodegroups/status
    verbs:
    - get
    - list
    - watch
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - resourcequotas
    - limitranges
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-view-projects
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目授权查看"
    theriseunion.io/description: "查看节点组项目授权信息"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-projects
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
spec:
  uiPermissions:
    - nodegroup/projects.view
  rules:
  - apiGroups:
    - resourcequotas.theriseunion.io
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: nodegroup-manage-projects
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目授权管理"
    theriseunion.io/description: "编辑节点组项目授权信息"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: nodegroup
    iam.theriseunion.io/category: nodegroup-projects
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/dependencies: "nodegroup-view-projects"
spec:
  uiPermissions:
    - nodegroup/projects.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - namespaces
    verbs:
    - '*'
