apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-admin
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "管理 Edge 平台上的所有资源"
  labels:
    theriseunion.io/managed: "true"
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  #TODO: update uiPermissions to platform/*.* when frontend supports it
  aggregationRoleTemplates:
    roleSelector:
      matchLabels:
        iam.theriseunion.io/aggregate-to-admin: ""

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-self-provisioner
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "创建租户空间并成为所创建的租户空间的管理员"
  labels:
    theriseunion.io/managed: "true"
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  aggregationRoleTemplates:
    templateNames:
      - platform-create-workspaces

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-regular
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "被邀请加入租户空间之前无法访问任何资源"
  labels:
    theriseunion.io/managed: "true"
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  aggregationRoleTemplates:
    roleSelector:
      matchLabels:
        iam.theriseunion.io/aggregate-to-regular: ""
        iam.theriseunion.io/scope: platform