{{- if index .Values "cert-manager" "enabled" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wait-for-cert-manager-crds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wait-for-cert-manager-crds
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wait-for-cert-manager-crds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-for-cert-manager-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wait-for-cert-manager-crds
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wait-for-cert-manager-crds
    spec:
      serviceAccountName: {{ .Release.Name }}-wait-for-cert-manager-crds
      restartPolicy: OnFailure
      containers:
      - name: wait-for-crds
        image: quanzhenglong.com/base/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for cert-manager CRDs to be available..."
          
          CRDS=(
            "certificates.cert-manager.io"
            "clusterissuers.cert-manager.io"
            "certificaterequests.cert-manager.io"
            "issuers.cert-manager.io"
            "challenges.acme.cert-manager.io"
            "orders.acme.cert-manager.io"
          )
          
          for crd in "${CRDS[@]}"; do
            echo "Checking CRD: $crd"
            until kubectl get crd "$crd" >/dev/null 2>&1; do
              echo "CRD $crd not found, waiting..."
              sleep 2
            done
            echo "CRD $crd found, waiting for it to be established..."
            kubectl wait --for=condition=established --timeout=60s crd/"$crd" || true
            echo "CRD $crd is established"
          done
          
          echo "All cert-manager CRDs are available and established!"
{{- end }}

