apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edge-controller.fullname" . }}
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
rules:
# Core Kubernetes resources
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
