# Host 集群组件配置
# 这些 Component CRs 定义了 Host 集群需要安装的所有组件
# 使用方式: kubectl apply -f components/host-components.yaml

---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-apiserver
  namespace: edge-system
  labels:
    app.kubernetes.io/name: edge-apiserver
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/part-of: edge-platform
    app.kubernetes.io/managed-by: component-controller
spec:
  type: apiserver
  enabled: true
  chart:
    name: edge-apiserver
    namespace: edge-system
    releaseName: edge-apiserver

---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-console
  namespace: edge-system
  labels:
    app.kubernetes.io/name: edge-console
    app.kubernetes.io/component: console
    app.kubernetes.io/part-of: edge-platform
    app.kubernetes.io/managed-by: component-controller
spec:
  type: console
  enabled: true
  chart:
    name: edge-console
    namespace: edge-system
    releaseName: edge-console

---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-monitoring
  namespace: observability-system
  labels:
    app.kubernetes.io/name: edge-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: edge-platform
    app.kubernetes.io/managed-by: component-controller
spec:
  type: monitoring
  enabled: true
  chart:
    name: edge-monitoring
    namespace: observability-system
    releaseName: edge-monitoring
