# Member 集群组件配置
# Member 集群不包含 console 组件
# 这些 Component CRs 通常由 Cluster Controller 自动创建，此文件仅供参考

---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-apiserver
  namespace: edge-system
  labels:
    app.kubernetes.io/name: edge-apiserver
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/part-of: edge-platform
    app.kubernetes.io/managed-by: component-controller
    cluster.theriseunion.io/role: member
spec:
  type: apiserver
  enabled: true
  chart:
    name: edge-apiserver
    namespace: edge-system
    releaseName: edge-apiserver

---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-monitoring
  namespace: observability-system
  labels:
    app.kubernetes.io/name: edge-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: edge-platform
    app.kubernetes.io/managed-by: component-controller
    cluster.theriseunion.io/role: member
spec:
  type: monitoring
  enabled: true
  chart:
    name: edge-monitoring
    namespace: observability-system
    releaseName: edge-monitoring
