{{- if .Values.edge.apiserver.config.deviceManager.enabledAggregator }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
  name: edge-system:edge-apiserver:aggregator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edge-system:edge-apiserver:aggregator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-aggregator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
  name: edge-system:edge-apiserver:aggregator
rules:
- nonResourceURLs:
  - /apis/vast.theriseunion.io/v1alpha1
  - /apis/vast.theriseunion.io/v1alpha1/*
  verbs:
  - get
- nonResourceURLs:
  - /apis
  - /apis/*
  verbs:
  - get
- nonResourceURLs:
  - /apis/vast.theriseunion.io
  - /apis/vast.theriseunion.io/*
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
# APIService with automatic CA bundle injection via cert-manager cainjector
# The cert-manager.io/inject-ca-from annotation tells cert-manager's cainjector
# to automatically inject the CA certificate from the specified Certificate resource
# into the caBundle field. This is the recommended approach per cert-manager best practices.
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
  name: v1alpha1.vast.theriseunion.io
  annotations:
    # cert-manager cainjector will automatically inject CA bundle from edge-ca-cert Certificate
    # Format: <namespace>/<certificate-name>
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/edge-ca-cert
spec:
  group: vast.theriseunion.io
  groupPriorityMinimum: 1000
  service:
    name: {{ include "edge-apiserver.fullname" . }}
    namespace: edge-system
    port: 8443
  # caBundle will be automatically injected by cert-manager cainjector
  # If manually set in values.yaml, it will override the automatic injection
  # Note: caBundle is at spec level, not under spec.service
  {{- if and .Values.certManager .Values.certManager.caBundle }}
  caBundle: {{ .Values.certManager.caBundle | quote }}
  {{- end }}
  version: v1alpha1
  versionPriority: 15
---
# NOTE: The Job for manual CA bundle injection has been removed.
# cert-manager's cainjector now automatically handles CA bundle injection
# via the cert-manager.io/inject-ca-from annotation on the APIService resource above.
# This approach is simpler, more reliable, and follows cert-manager best practices.
{{- end }}