---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: apiserver-project
    app.kubernetes.io/instance: apiserver-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: apiserver-project
  name: edge-apiserver-cert
  namespace: edge-system
spec:
  dnsNames:
  - {{ include "edge-apiserver.fullname" . }}.edge-system.svc
  - {{ include "edge-apiserver.fullname" . }}.edge-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: edge-selfsigned-issuer
  secretName: apiserver-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: apiserver-project
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: apiserver-project
  name: edge-selfsigned-issuer
  namespace: edge-system
spec:
  selfSigned: {}