apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edge-apiserver.fullname" . }}
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# Edge IAM resources
- apiGroups: ["iam.theriseunion.io"]
  resources: ["*"]
  verbs: ["*"]
# Tenant resources
- apiGroups: ["tenant.theriseunion.io"]
  resources: ["*"]
  verbs: ["*"]
# Scope resources (Cluster, Workspace, NodeGroup, etc.)
- apiGroups: ["scope.theriseunion.io"]
  resources: ["*"]
  verbs: ["*"]
# Edge installer resources
- apiGroups: ["installer.edge.theriseunion.io"]
  resources: ["*"]
  verbs: ["*"]