apiVersion: scope.theriseunion.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Values.edge.cluster.name | default "host-cluster" }}
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
    cluster.theriseunion.io/role: "host"
spec:
  enable: {{ .Values.edge.cluster.enabled | default true }}
  provider: {{ .Values.edge.cluster.provider | default "Kubernetes" }}
  joinFederation: {{ .Values.edge.cluster.joinFederation | default false }}
  externalKubeAPIEnabled: {{ .Values.edge.cluster.externalKubeAPIEnabled | default false }}
  connection:
    type: {{ .Values.edge.cluster.connection.type | default "direct" }}
    kubernetesAPIEndpoint: {{ .Values.edge.cluster.connection.kubernetesAPIEndpoint | default "https://kubernetes.default.svc:443" }}
    {{- if .Values.edge.cluster.connection.theriseunionAPIEndpoint }}
    theriseunionAPIEndpoint: {{ .Values.edge.cluster.connection.theriseunionAPIEndpoint }}
    {{- end }}