# RoleTemplates - 角色模板定义
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-create
  annotations:
    iam.theriseunion.io/role-template-rules: '{"workspaces": "create"}'
  labels:
    iam.theriseunion.io/category: workspace-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  description:
    en: Create workspaces.
    zh: 创建租户空间。
  displayName:
    en: Workspace Creation
    zh: 租户空间创建
  rules:
  - apiGroups:
    - scope.theriseunion.io
    resources:
    - workspaces
    - workspacetemplates
    verbs:
    - create
    - get
    - list
    - watch
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage
  annotations:
    iam.theriseunion.io/role-template-rules: '{"workspaces": "manage"}'
  labels:
    iam.theriseunion.io/category: workspace-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  description:
    en: Manage all workspaces and workspace resources.
    zh: 管理所有租户空间和租户空间下的资源。
  displayName:
    en: Workspace Management
    zh: 租户空间管理
  rules:
  - apiGroups:
    - '*'
    resources:
    - namespaces
    - workspaces
    - workspacetemplates
    - workspaceroles
    - workspacemembers
    - workspacerolebindings
    verbs:
    - '*'
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-view
  annotations:
    iam.theriseunion.io/role-template-rules: '{"workspaces": "view"}'
  labels:
    iam.theriseunion.io/category: workspace-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  description:
    en: View all workspaces and workspace resources.
    zh: 查看所有工作空间和租户空间下的资源。
  displayName:
    en: Workspace View
    zh: 租户空间查看
  rules:
  - apiGroups:
    - '*'
    resources:
    - namespaces
    - workspaces
    - workspacetemplates
    - workspaceroles
    - workspacemembers
    - workspacerolebindings
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch

# IAMRoles - 基于RoleTemplate的角色定义
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: anonymous
  annotations:
    edge.io/description: '{"zh": "匿名用户基础访问权限", "en": "Basic access for anonymous users"}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "匿名用户基础访问权限", "en": "Basic access for anonymous users"}'
  labels:
    iam.theriseunion.io/managed: "true"
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  rules:
  # 1. Kubernetes 核心资源 - 基础查询
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list

  # 2. Edge 租户资源 - 允许查询但通过 ABAC 过滤结果
  - apiGroups:
    - "tenant"
    resources:
    - workspaces
    - clusters
    - nodegroups
    verbs:
    - list

  # 3. 平台配置资源 - 允许认证用户查看平台配置（主题、logo等）
  - apiGroups:
    - "config.theriseunion.io"
    resources:
    - configs
    verbs:
    - get
    - list

  # 4. IAM 权限查询 - 允许用户查询自己的权限
  - apiGroups:
    - "iam.theriseunion.io"
    resources:
    - permissions
    verbs:
    - get
    - list

  # 5. 监控资源 - 允许所有用户查看监控数据（最宽松策略）
  - apiGroups:
    - "monitoring.theriseunion.io"
    resources:
    - cluster
    - workspaces
    - namespaces
    - nodegroups
    - nodes
    - query
    verbs:
    - get
    - list

  # 6. 非资源URL - K8s 和 OIDC 标准
  - nonResourceURLs:
    - /api
    - /api/v1
    - /apis
    - /apis/*
    - /oapis
    - /oapis/*
    - /oauth/userinfo
    - /version
    - /healthz
    verbs:
    - get
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: cluster-admin
  annotations:
    edge.io/creator: system
    edge.io/description: '{"zh": "管理集群中的所有资源。", "en": "Manage all resources in cluster."}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "管理集群中的所有资源。", "en": "Manage all resources in cluster."}'
    theriseunion.io/role-templates: ""
  labels:
    iam.theriseunion.io/category: cluster-management
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/scope-value: host
spec:
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: cluster-viewer
  annotations:
    edge.io/creator: system
    edge.io/description: '{"zh": "查看集群中的所有资源。", "en": "View all resources in cluster."}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "查看集群中的所有资源。", "en": "View all resources in cluster."}'
    theriseunion.io/role-templates: ""
  labels:
    iam.theriseunion.io/category: cluster-management
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/scope-value: host
spec:
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
  uiPermissions:
  - cluster/node.view
  - cluster/namespace.view
  - cluster/workload.view
  - cluster/storage.view
  - cluster/network.view
  - cluster/config.view
  - cluster/monitoring.view
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-admin
  annotations:
    edge.io/creator: system
    edge.io/description: '{"zh": "管理 Edge 平台上的所有资源。", "en": "Manage all resources on Edge platform."}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "管理 Edge 平台上的所有资源。", "en": "Manage all resources on Edge platform."}'
    theriseunion.io/role-templates: workspace-create,workspace-manage,workspace-view
  labels:
    edge.io/managed: "true"
    iam.theriseunion.io/category: platform-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  # 平台管理员UI权限
  uiPermissions:
    # 用户管理权限
    - platform/user.view
    - platform/user.manage
    # 角色管理权限
    - platform/role.view
    - platform/role.manage
    # 工作空间管理权限
    - platform/workspace.view
    - platform/workspace.manage
    # 集群管理权限
    - platform/cluster.view
    - platform/cluster.manage
    # 平台设置权限
    - platform/settings.view
    - platform/settings.manage
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - /api/*
    - /apis/*
    - /healthz
    - /metrics
    - /oapis/*
    verbs:
    - '*'
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-regular
  annotations:
    edge.io/creator: system
    edge.io/description: '{"zh": "被邀请加入租户空间之前无法访问任何资源。", "en": "Cannot access any resources before being invited to workspaces."}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "被邀请加入租户空间之前无法访问任何资源。", "en": "Cannot access any resources before being invited to workspaces."}'
    theriseunion.io/role-templates: ""
  labels:
    iam.theriseunion.io/category: platform-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  # UI权限定义：基础用户只能查看自己加入的租户空间
  uiPermissions:
    - platform/workspace.view    # 查看自己加入的租户空间（后端会根据成员关系过滤）
  rules:
  # 基础查询权限 - 允许列出资源，但后端会根据成员关系过滤结果
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
  - apiGroups:
    - tenant
    - tenant.theriseunion.io
    resources:
    - workspaces
    - clusters
    - namespaces
    verbs:
    - get
    - list
    - watch
  # 权限查询 - 允许用户查询自己的权限
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - permissions
    verbs:
    - get
    - list
  # 非资源URL访问
  - nonResourceURLs:
    - /api
    - /api/v1
    - /apis
    - /apis/*
    - /oapis
    - /oapis/*
    - /oauth/userinfo
    - /version
    - /healthz
    verbs:
    - get
---
apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: platform-self-provisioner
  annotations:
    edge.io/creator: system
    edge.io/description: '{"zh": "创建租户空间并成为所创建的租户空间的管理员。", "en": "Create workspaces and become administrator of created workspaces."}'
    theriseunion.io/creator: system
    theriseunion.io/description: '{"zh": "创建租户空间并成为所创建的租户空间的管理员。", "en": "Create workspaces and become administrator of created workspaces."}'
    theriseunion.io/role-templates: workspace-create
  labels:
    edge.io/managed: "true"
    iam.theriseunion.io/category: cluster-management
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  # UI权限定义：允许查看和创建租户空间
  uiPermissions:
    - platform/workspace.view    # 查看租户空间列表
    - platform/workspace.create  # 创建新租户空间
    - platform/cluster.view      # 查看集群列表（创建租户空间时需要选择集群）
  rules:
  - apiGroups:
    - ""
    - cluster.theriseunion.io
    resources:
    - clusters
    - clustertemplates
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - scope.theriseunion.io
    - tenant.theriseunion.io
    resources:
    - workspaces
    - workspacetemplates
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - clustermembers
    - clusterroles
    verbs:
    - get
    - list
    - watch