{{- if .Values.nodelocaldns.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodelocaldns-edge
  namespace: kube-system
  labels:
    {{- include "openyurt-addition.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
