# OpenYurt 1.3 yurt-manager 配置

# settings for log print
log:
  # log level for yurt-manager
  level: 4

replicaCount: 1
nameOverride: ""

image:
  registry: openyurt
  repository: yurt-manager
  tag: v1.3.4

ports:
  metrics: 10271
  healthProbe: 10272
  webhook: 10273

# format should be "foo,-bar,*"
controllers: ""

# format should be "foo,*"
disableIndependentWebhooks: ""

# resources of yurt-manager container
resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
