apiVersion: iam.theriseunion.io/v1alpha1
kind: IAMRole
metadata:
  name: anonymous
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "匿名用户基础访问权限"
    iam.theriseunion.io/ignore-aggregate: "true"
  labels:
    iam.theriseunion.io/managed: "true"
    iam.theriseunion.io/scope: platform
    iam.theriseunion.io/scope-value: global
spec:
  rules:
  # 1. Kubernetes 核心资源 - 基础查询
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list

  # 2. Edge 租户资源 - 允许查询但通过 ABAC 过滤结果
  - apiGroups:
    - "tenant"
    resources:
    - workspaces
    - clusters
    - nodegroups
    verbs:
    - list

  # 3. 平台配置资源 - 允许认证用户查看平台配置（主题、logo等）
  - apiGroups:
    - "config.theriseunion.io"
    resources:
    - configs
    verbs:
    - get
    - list

  # 4. IAM 权限查询 - 允许用户查询自己的权限
  - apiGroups:
    - "iam.theriseunion.io"
    resources:
    - permissions
    verbs:
    - get
    - list

  # 5. 监控资源 - 允许所有用户查看监控数据（最宽松策略）
  - apiGroups:
    - "monitoring.theriseunion.io"
    resources:
    - cluster
    - workspaces
    - namespaces
    - nodegroups
    - nodes
    - query
    verbs:
    - get
    - list

  # 6. 非资源URL - K8s 和 OIDC 标准
  - nonResourceURLs:
    - /api
    - /api/v1
    - /apis
    - /apis/*
    - /oapis
    - /oapis/*
    - /oauth/userinfo
    - /version
    - /healthz
    verbs:
    - get