apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: cluster-basic
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "Cluster 级基础权限"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/aggregate-to-regular: ""
spec:
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - clusters
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - monitoring.theriseunion.io
    resources:
    - cluster
    - cluster/metrics
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "集群节点查看"
    theriseunion.io/description: "允许查看当前集群里的集群节点"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-nodes
spec:
  uiPermissions:
    - cluster/nodes.view
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - nodes
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - monitoring.theriseunion.io
    resources:
    - nodes/metrics
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
      - api/v1/namespaces/_all_/events
    verbs:
      - get
      - list
      - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "集群节点管理"
    theriseunion.io/description: "管理当前集群里的集群节点"
    iam.theriseunion.io/dependencies: "cluster-view-nodes"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-nodes
spec:
  uiPermissions:
    - cluster/nodes.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - nodes
    - pods
    verbs:
    - '*'
  - apiGroups:
    - terminal.theriseunion.io
    resources:
    - nodegroups
    verbs:
    - get
    - list
  - apiGroups:
    - terminal.theriseunion.io
    resources:
    - nodes
    - nodes/exec
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点组查看"
    theriseunion.io/description: "允许查看当前集群里的节点组"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-nodegroups
spec:
  uiPermissions:
    - cluster/nodegroups.view
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - nodegroups
    - nodegroups/nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - monitoring.theriseunion.io
    resources:
    - nodegroups/metrics
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "节点组创建"
    theriseunion.io/description: "创建节点组并成为管理员"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-self-provisioner: ""
  name: cluster-create-nodegroups
spec:
  uiPermissions:
    - cluster/nodegroups.create
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - nodegroups
    verbs:
    - create

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "配置查看"
    theriseunion.io/description: "查看当前集群里的配置资源"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-configurations
spec:
  uiPermissions:
    - cluster/configurations.view
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "配置管理"
    theriseunion.io/description: "管理当前集群里的配置资源"
    iam.theriseunion.io/dependencies: "cluster-view-configurations"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-resource
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-configurations
spec:
  uiPermissions:
    - cluster/configurations.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "应用负载查看"
    theriseunion.io/description: "允许查看当前集群里的应用负载资源"
    iam.theriseunion.io/dependencies: "cluster-view-configurations, cluster-view-pv"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-workload
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-workloads
spec:
  uiPermissions:
    - cluster/workloads.view
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - endpoints
    - limitranges
    - podtemplates
    - replicationcontrollers
    - resourcequotas
    - secrets
    - serviceaccounts
    - services
    - controllerrevisions
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
    - cronjobs
    - jobs
    - events
    - ingresses
    - router
    - pods
    - pods/log
    - pods/containers
    - namespacenetworkpolicies
    - networkpolicies
    - podsecuritypolicies
    - servicepolicies
    - quotas
    - abnormalworkloads
    - workloads
    - strategies
    - horizontalpodautoscalers
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "应用负载管理"
    theriseunion.io/description: "管理当前集群里的应用负载资源"
    iam.theriseunion.io/dependencies: "cluster-view-workloads"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-workload
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-workloads
spec:
  uiPermissions:
    - cluster/workloads.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - endpoints
    - limitranges
    - podtemplates
    - replicationcontrollers
    - resourcequotas
    - secrets
    - serviceaccounts
    - services
    - controllerrevisions
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
    - cronjobs
    - jobs
    - events
    - ingresses
    - router
    - pods
    - pods/log
    - pods/containers
    - namespacenetworkpolicies
    - networkpolicies
    - podsecuritypolicies
    - servicepolicies
    - quotas
    - abnormalworkloads
    - workloads
    - strategies
    - horizontalpodautoscalers
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目查看"
    theriseunion.io/description: "允许查看当前集群里的项目信息"
    iam.theriseunion.io/dependencies: "cluster-view-workloads"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-namespace
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-namespaces
spec:
  uiPermissions:
    - cluster/namespaces.view
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:  
    - namespaces
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目管理"
    theriseunion.io/description: "管理当前集群里的项目信息"
    iam.theriseunion.io/dependencies: "cluster-manage-workloads"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-namespace
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-namespaces
spec:
  uiPermissions:
    - cluster/namespaces.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:  
    - namespaces
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "存储类查看"
    theriseunion.io/description: "允许查看存储类信息"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/category: cluster-storage
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-sc
spec:
  uiPermissions:
    - cluster/storages.view
  rules:
    - apiGroups:
        - resources.theriseunion.io
      resources:
        - storageclasses
      verbs:
        - list
        - get
        - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "存储类管理"
    theriseunion.io/description: "管理存储类"
    iam.theriseunion.io/dependencies: "cluster-view-sc"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/category: cluster-storage
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-sc
spec:
  uiPermissions:
    - cluster/storages.manage
  rules:
    - apiGroups:
        - resources.theriseunion.io
      resources:
        - 'storageclasses'
      verbs:
        - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "持久卷查看"
    theriseunion.io/description: "允许查看持久卷相关信息"
    iam.theriseunion.io/dependencies: "cluster-view-sc"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/category: cluster-storage
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-pv
spec:
  uiPermissions:
    - cluster/storages.view
    - cluster/pv.view
  rules:
    - apiGroups:
        - resources.theriseunion.io
      resources:
        - persistentvolumes
        - persistentvolumeclaims
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - ""
      resources:
        - namespaces/events
        - events
      verbs:
        - list
        - get
        - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "持久卷管理"
    theriseunion.io/description: "管理持久卷相关信息"
    iam.theriseunion.io/dependencies: "cluster-view-pv"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/category: cluster-storage
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-pv
spec:
  uiPermissions:
    - cluster/pv.manage
  rules:
    - apiGroups:
        - resources.theriseunion.io
      resources:
        - persistentvolumes
        - persistentvolumeclaims
      verbs:
        - "*"

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "集群设置"
    theriseunion.io/description: "允许查看集群设置信息"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-settings
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
    iam.theriseunion.io/aggregate-to-self-provisioner: ""
  name: cluster-view-settings
spec:
  uiPermissions:
    - cluster/settings.view
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - clusters
    - nodes
    - storageclasses
    - configmaps
    verbs:
    - get
    - list
  - nonResourceURLs:
      - version
      - oapis/version
    verbs:
      - get
      - list
      - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "集群设置管理"
    theriseunion.io/description: "管理集群配置信息"
    iam.theriseunion.io/dependencies: "cluster-view-settings"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-settings
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-settings
spec:
  uiPermissions:
    - cluster/settings.manage
  rules:
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - clusters
    - nodes
    - storageclasses
    - configmaps
    verbs:
    - '*'
  - nonResourceURLs:
      - version
      - oapis/version
    verbs:
      - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色查看"
    theriseunion.io/description: "允许查看集群下角色"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-roles
spec:
  uiPermissions:
    - cluster/settings.view
    - cluster/roles.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - roles
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色管理"
    theriseunion.io/description: "管理集群下角色"
    iam.theriseunion.io/dependencies: "cluster-view-roles"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-roles
spec:
  uiPermissions:
    - cluster/roles.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - roles
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员查看"
    theriseunion.io/description: "允许查看集群下成员信息"
    iam.theriseunion.io/dependencies: "cluster-view-roles"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
  name: cluster-view-members
spec:
  uiPermissions:
    - cluster/settings.view
    - cluster/members.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - members
    - roles
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员管理"
    theriseunion.io/description: "管理集群下所有成员"
    iam.theriseunion.io/dependencies: "cluster-view-members"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
  name: cluster-manage-members
spec:
  uiPermissions:
    - cluster/members.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - members
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: cluster-view-devices
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "算力查看"
    theriseunion.io/description: "查看当前集群下算力资源"
    iam.theriseunion.io/dependencies: "cluster-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-devices
    iam.theriseunion.io/aggregate-to-viewer: ""
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - cluster/devices.view
  rules:
  - apiGroups:
    - device.vast.theriseunion.io
    resources:
    - devices
    - devicemodels
    - computetemplates
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: cluster-manage-devices
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "算力管理"
    theriseunion.io/description: "管理当前集群下算力资源"
    iam.theriseunion.io/dependencies: "cluster-view-devices"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-devices
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - cluster/devices.manage
  rules:
  - apiGroups:
    - device.vast.theriseunion.io
    resources:
    - devices
    - devicemodels
    - computetemplates
    verbs:
    - "*"

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: cluster-manage-monitoring
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "监控告警管理"
    theriseunion.io/description: "允许管理当前集群下的监控告警"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: cluster
    iam.theriseunion.io/category: cluster-monitoring
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - cluster/monitoring.manage
  rules:
  - apiGroups:
      - duty.theriseunion.io
    resources:
      - "*"
    verbs:
      - "*"
