apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-basic
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/description: "Workspace 级基础权限"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/aggregate-to-regular: ""
spec:
  uiPermissions:
    - workspace/basic.view
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - workspaces
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - resources.theriseunion.io
    resources:
    - nodes
    verbs:
    - get
    - watch
    - list
  - nonResourceURLs:
      - /api/v1alpha1/events
    verbs:
      - get
      - list
      - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-view-projects
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目查看"
    theriseunion.io/description: "允许查看当前租户空间下的项目"
    iam.theriseunion.io/dependencies: "workspace-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-project-management
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-regular: ""
    iam.theriseunion.io/aggregate-to-viewer: ""
spec:
  uiPermissions:
    - workspace/projects.view
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-create-projects
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目创建"
    theriseunion.io/description: "允许在当前租户空间下创建项目并成为此项目管理员"
    iam.theriseunion.io/dependencies: "workspace-view-projects"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-project-management
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-self-provisioner: ''
spec:
  uiPermissions:
    - workspace/projects.create
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - namespaces
    verbs:
    - create

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage-projects
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "项目管理"
    theriseunion.io/description: "管理当前租户空间下项目"
    iam.theriseunion.io/dependencies: "workspace-create-projects"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-project-management
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - workspace/projects.manage
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - namespaces
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-view-settings
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "设置查看"
    theriseunion.io/description: "查看当前租户空间的设置"
    iam.theriseunion.io/dependencies: "workspace-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-settings
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-regular: ''
    iam.theriseunion.io/aggregate-to-self-provisioner: ''
    iam.theriseunion.io/aggregate-to-viewer: ''
spec:
  uiPermissions:
    - workspace/settings.view
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - workspaces
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage-settings
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "设置管理"
    theriseunion.io/description: "管理当前租户空间的设置"
    iam.theriseunion.io/dependencies: "workspace-view-settings"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-settings
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - workspace/settings.manage
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - workspaces
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-view-roles
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色查看"
    theriseunion.io/description: "查看当前租户空间下的角色"
    iam.theriseunion.io/dependencies: "workspace-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ''
spec:
  uiPermissions:
    - workspace/roles.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - roles
    verbs:
    - list
    - get
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage-roles
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "角色管理"
    theriseunion.io/description: "管理当前租户空间下的角色"
    iam.theriseunion.io/dependencies: "workspace-view-roles"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - workspace/roles.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - roles
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-view-members
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员查看"
    theriseunion.io/description: "查看当前租户空间下的成员"
    iam.theriseunion.io/dependencies: "workspace-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
    iam.theriseunion.io/aggregate-to-viewer: ''
spec:
  uiPermissions:
    - workspace/members.view
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - members
    - roles
    verbs:
    - get
    - list
    - watch

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage-members
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "成员管理"
    theriseunion.io/description: "管理当前租户空间下的成员"
    iam.theriseunion.io/dependencies: "workspace-view-members"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-access-control
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - workspace/members.manage
  rules:
  - apiGroups:
    - iam.theriseunion.io
    resources:
    - members
    verbs:
    - '*'

---
apiVersion: iam.theriseunion.io/v1alpha1
kind: RoleTemplate
metadata:
  name: workspace-manage-application
  annotations:
    theriseunion.io/creator: system
    theriseunion.io/alias-name: "应用管理"
    theriseunion.io/description: "管理当前租户空间下的应用"
    iam.theriseunion.io/dependencies: "workspace-basic"
  labels:
    theriseunion.io/managed: 'true'
    iam.theriseunion.io/scope: workspace
    iam.theriseunion.io/category: workspace-application-management
    iam.theriseunion.io/aggregate-to-admin: ""
spec:
  uiPermissions:
    - workspace/applications.manage
  rules:
  - apiGroups:
    - tenant.theriseunion.io
    resources:
    - workspaces/namespaces
    verbs:
    - list
    - get
  - apiGroups:
    - app.theriseunion.io
    resources:
    - appcategories
    verbs:
    - list
    - get
  - apiGroups:
    - device.vast.theriseunion.io
    resources:
    - devicemodels
    verbs:
    - list
    - get
  - apiGroups:
    - image.theriseunion.io
    resources:
    - namespaces/repositories
    verbs:
    - list
    - get
  - apiGroups:
    - app.theriseunion.io
    resources:
    - applications
    - workspaces/applications
    - applications/versions
    verbs:
    - '*'
