# OpenYurt raven-agent Helm values (可选组件)
# raven-agent 提供边缘节点间的跨网络域通信能力
# 如果边缘节点需要跨不同网络域通信，建议安装此组件

# 镜像配置
# 支持使用私有镜像仓库
# 使用公共镜像: openyurt/raven-agent
# 使用私有镜像: quanzhenglong.com/edge/raven-agent
image:
  repository: quanzhenglong.com/edge/raven-agent
  tag: v0.4.1
  pullPolicy: IfNotPresent

# 如果使用私有镜像仓库，需要配置 imagePullSecrets
# 创建 secret: kubectl create secret docker-registry edge-registry \
#   --docker-server=quanzhenglong.com \
#   --docker-username=edge_admin \
#   --docker-password=YOUR_PASSWORD \
#   -n kube-system
imagePullSecrets: []
  # - name: edge-registry

# 副本数（DaemonSet 模式，自动在所有节点上运行）
# 注意：raven-agent 以 DaemonSet 方式运行，replicaCount 参数可能不生效

# 资源限制
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 节点选择器 - 可以选择性地只在边缘节点上运行
nodeSelector:
  # 如果需要只在边缘节点上运行，取消下面的注释
  # node.theriseunion.io/type: edge

# 容忍度 - 允许在所有节点上运行
tolerations:
  - operator: Exists

# Raven 网络配置
network:
  # VPN 端口
  vpnPort: 4500
  # 代理端口
  proxyPort: 10262

# Raven Gateway 配置
gateway:
  # 是否启用 Gateway 功能
  enabled: true
  # Gateway 副本数
  replicas: 1

# 日志级别
logLevel: 2

# Metrics 配置
metrics:
  enabled: true
  port: 8080

# 健康检查配置
healthCheck:
  enabled: true
  port: 10270

# 注意事项：
# 1. raven-agent 是可选组件，主要用于边缘节点间的跨网络域通信
# 2. 如果边缘节点都在同一网络域内，可以不安装此组件
# 3. raven-agent 以 DaemonSet 方式运行，会自动部署到所有匹配的节点
# 4. 需要确保边缘节点间的 VPN 端口（默认 4500）可以互相访问
