# OpenYurt yurthub Helm values
# yurthub 是边缘节点上的关键组件，作为节点和云端 API Server 之间的代理

# Kubernetes API Server 地址
# 必填项：需要设置为集群的 API Server 地址
# 示例：https://192.168.1.102:6443
kubernetesServerAddr: ""

# 镜像配置
# 支持使用私有镜像仓库
# 使用公共镜像: openyurt/yurthub
# 使用私有镜像: quanzhenglong.com/edge/yurthub
image:
  repository: quanzhenglong.com/edge/yurthub
  tag: v1.6.0
  pullPolicy: IfNotPresent

# 如果使用私有镜像仓库，需要配置 imagePullSecrets
# 创建 secret: kubectl create secret docker-registry edge-registry \
#   --docker-server=quanzhenglong.com \
#   --docker-username=edge_admin \
#   --docker-password=YOUR_PASSWORD \
#   -n kube-system
imagePullSecrets: []
  # - name: edge-registry

# yurthub 工作模式
# - edge: 边缘模式（适用于边缘节点）
# - cloud: 云端模式（适用于云端节点）
workingMode: edge

# yurthub 命令行参数
# ⚠️ CRITICAL: hub-cert-organizations 参数对 CNI 插件至关重要
# 如果缺少此参数，CNI 插件（如 Calico）将无法通过 yurthub 访问 API Server
# 导致 Pod 停留在 ContainerCreating 状态，错误信息为 "TLS handshake timeout"
extraArgs:
  # 必须包含此参数，确保证书包含正确的组织名称
  - --hub-cert-organizations=system:nodes
  # 日志级别
  - --v=2
  # 绑定地址
  - --bind-address=127.0.0.1
  # 其他可选参数
  # - --enable-dummy-if=true
  # - --enable-iptables=true

# 端口配置
ports:
  # yurthub HTTP 端口
  serverPort: 10261
  # yurthub HTTPS 端口
  securePort: 10268
  # Profiling 端口
  profilingPort: 10267

# 资源限制
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 节点选择器 - yurthub 通过 YurtStaticSet 自动部署到边缘节点
# 这里的配置主要用于 YurtStaticSet controller
nodeSelector:
  # 自动部署到标记为 edge 的节点
  node.theriseunion.io/type: edge

# 容忍度 - 允许在边缘节点上运行
tolerations:
  - operator: Exists

# 持久化存储配置
persistence:
  # 启用持久化存储，用于缓存 API 对象
  enabled: true
  # 存储路径
  hostPath: /var/lib/yurthub
  # 存储大小
  size: 2Gi

# Bootstrap 配置
bootstrap:
  # Bootstrap token 文件路径
  file: /var/lib/yurthub/bootstrap-hub.conf

# 证书配置
certs:
  # 证书目录
  certDir: /var/lib/yurthub/pki
  # 证书有效期（天）
  certDuration: 365

# 缓存配置
cache:
  # 启用缓存
  enabled: true
  # 缓存策略
  # - local: 仅使用本地缓存
  # - remote: 优先使用远程，本地缓存作为备份
  strategy: remote

# 健康检查配置
healthCheck:
  # 存活探测
  livenessProbe:
    enabled: true
    httpGet:
      path: /v1/healthz
      port: 10267
    initialDelaySeconds: 300
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
  # 就绪探测
  readinessProbe:
    enabled: true
    httpGet:
      path: /v1/readyz
      port: 10267
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3

# 注意事项：
# 1. kubernetesServerAddr 必须设置为集群的 API Server 地址
# 2. extraArgs 中的 --hub-cert-organizations=system:nodes 参数至关重要
# 3. yurthub 通过 YurtStaticSet 以静态 Pod 方式运行在边缘节点上
# 4. 边缘节点加入集群时，需要提供正确的 bootstrap token
