# OpenYurt yurt-manager Helm values
# yurt-manager 是 OpenYurt 的核心控制器，负责管理边缘节点池、应用等

# 镜像配置
# 支持使用私有镜像仓库
# 使用公共镜像: registry: openyurt, repository: yurt-manager
# 使用私有镜像: registry: quanzhenglong.com/edge, repository: yurt-manager
image:
  registry: quanzhenglong.com/edge
  repository: yurt-manager
  tag: v1.6.0
  pullPolicy: IfNotPresent

# 如果使用私有镜像仓库，需要配置 imagePullSecrets
# 创建 secret: kubectl create secret docker-registry edge-registry \
#   --docker-server=quanzhenglong.com \
#   --docker-username=edge_admin \
#   --docker-password=YOUR_PASSWORD \
#   -n kube-system
imagePullSecrets: []
  # - name: edge-registry

# 副本数
replicaCount: 1

# 资源限制
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 节点选择器 - 确保运行在控制平面节点
nodeSelector:
  node-role.kubernetes.io/control-plane: ""

# 容忍度 - 允许调度到控制平面节点
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# 日志级别
logLevel: 2

# Webhook 配置
webhook:
  enabled: true
  port: 9443
  certDir: /tmp/k8s-webhook-server/serving-certs

# Metrics 配置
metrics:
  enabled: true
  port: 8080

# Leader Election 配置
leaderElection:
  enabled: true
  namespace: kube-system
