{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeedge.serviceAccountName" . }}
  namespace: {{ include "kubeedge.namespace" . }}
  labels:
    {{- include "kubeedge.cloudcore.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.iptablesManager.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iptables-manager-sa
  namespace: {{ include "kubeedge.namespace" . }}
  labels:
    {{- include "kubeedge.iptables.labels" . | nindent 4 }}
{{- end }}
