{{- if and .Values.global.enabled .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: edge-alertmanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-alertmanager
    component: alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - port: {{ .Values.alertmanager.service.port }}
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: edge-alertmanager
{{- end }}