{{- if and .Values.global.enabled .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-alertmanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-alertmanager
    component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-alertmanager
  template:
    metadata:
      labels:
        app: edge-alertmanager
        component: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
        imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
        ports:
        - containerPort: 9093
          name: web
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        - "--web.external-url=http://localhost:9093"
        - "--cluster.listen-address="
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          {{- toYaml .Values.alertmanager.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
      - name: alertmanager-config
        configMap:
          name: edge-alertmanager-config
      - name: alertmanager-storage
        emptyDir: {}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
{{- end }}