{{- if and .Values.global.enabled .Values.grafana.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-grafana-datasources
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-grafana
    component: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    {{- range .Values.grafana.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      url: {{ .url }}
      access: {{ .access }}
      isDefault: {{ .isDefault }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-grafana-dashboard-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-grafana
    component: grafana
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'edge-dashboards'
      orgId: 1
      folder: 'Edge Monitoring'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
{{- end }}