{{- if and .Values.global.enabled .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: edge-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-grafana
    component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: 3000
    protocol: TCP
    name: web
  selector:
    app: edge-grafana
{{- end }}