{{- if and .Values.global.enabled .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-grafana-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-grafana
    component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.grafana.persistence.storageClassName }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  {{- end }}
{{- end }}