{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-kube-state-metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-kube-state-metrics
    component: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-kube-state-metrics
  template:
    metadata:
      labels:
        app: edge-kube-state-metrics
        component: kube-state-metrics
    spec:
      serviceAccountName: edge-kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: {{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}
        imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: telemetry
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.kubeStateMetrics.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
{{- end }}