{{- if and .Values.global.enabled .Values.monitoringService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: monitoring-service
    component: monitoring-service
data:
  config.json: |
    {
      "Server": {
        "InsecurePort": 9083
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-service-log-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: monitoring-service
    component: monitoring-service
data:
  log-config.yaml: |
    Level: info
    EncoderType: console
    Path: /tmp
    FileName: monitoring-service.log
    MaxSize: 20
    MaxBackups: 5
    MaxAge: 30
    LocalTime: false
    Compress: true
    OutMod: both
{{- end }}
