apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: namespace-recording-rules
  namespace: observability-system
  labels:
    prometheus: kube-prometheus
    role: recording-rules
    layer: namespace
    release: edge-monitoring
spec:
  groups:
    # ========================================================================
    # Namespace-level Aggregation Recording Rules
    # Purpose: Application-level namespace resource metrics aggregation
    # Priority: P2
    # Dependencies: kube-state-metrics, cadvisor
    # ========================================================================
    - name: namespace-aggregation-rules
      interval: 30s
      rules:
        # =====================================================
        # Pod and Workload Count (aggregated by namespace)
        # =====================================================

        # Namespace pod count
        - record: namespace:kube_pod:count
          expr: |
            count by (cluster, namespace) (
              kube_pod_info
            )

        # Namespace deployment count
        - record: namespace:kube_deployment:count
          expr: |
            count by (cluster, namespace) (
              kube_deployment_spec_replicas
            )

        # Namespace statefulset count
        - record: namespace:kube_statefulset:count
          expr: |
            count by (cluster, namespace) (
              kube_statefulset_replicas
            )

        # Namespace daemonset count
        - record: namespace:kube_daemonset:count
          expr: |
            count by (cluster, namespace) (
              kube_daemonset_status_desired_number_scheduled
            )

        # Namespace job count
        - record: namespace:kube_job:count
          expr: |
            count by (cluster, namespace) (
              kube_job_info
            )

        # Namespace cronjob count
        - record: namespace:kube_cronjob:count
          expr: |
            count by (cluster, namespace) (
              kube_cronjob_info
            )

        # Namespace service count
        - record: namespace:kube_service:count
          expr: |
            count by (cluster, namespace) (
              kube_service_info
            )

        # =====================================================
        # CPU metrics (aggregated by namespace)
        # =====================================================

        - record: namespace:container_cpu_usage_seconds:sum_rate
          expr: |
            sum by (cluster, namespace) (
              irate(container_cpu_usage_seconds_total[5m])
            )

        # =====================================================
        # Memory metrics (aggregated by namespace)
        # =====================================================

        - record: namespace:container_memory_usage_bytes:sum
          expr: |
            sum by (cluster, namespace) (
              container_memory_usage_bytes
            )

        # =====================================================
        # Network metrics (aggregated by namespace)
        # =====================================================

        - record: namespace:container_network_receive_packets:sum_rate
          expr: |
            sum by (cluster, namespace) (
              irate(container_network_receive_packets_total{interface!="lo"}[5m])
            )

        - record: namespace:container_network_transmit_packets:sum_rate
          expr: |
            sum by (cluster, namespace) (
              irate(container_network_transmit_packets_total{interface!="lo"}[5m])
            )
