apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-recording-rules
  namespace: observability-system
  labels:
    prometheus: kube-prometheus
    role: recording-rules
    layer: node
    release: edge-monitoring
spec:
  groups:
    # ========================================================================
    # Node-level Recording Rules
    # Purpose: Pre-aggregate node-level resource metrics for performance
    # Priority: P1 - Foundation for nodegroup and cluster aggregations
    # Dependencies: node-exporter, kube-state-metrics, cadvisor
    # ========================================================================
    - name: node-cpu-metrics
      interval: 30s
      rules:
        # Node CPU total cores
        # Use label_replace to copy node -> instance for Monitoring Service compatibility
        - record: node_cpu_total
          expr: |
            label_replace(
              count by (cluster, node) (
                node_cpu_seconds_total{job="node-exporter", mode="idle"}
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node CPU usage (cores in use)
        - record: node_cpu_usage
          expr: |
            label_replace(
              sum by (cluster, node) (
                rate(node_cpu_seconds_total{job="node-exporter", mode!="idle"}[5m])
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node CPU utilisation (0-1 ratio)
        - record: node_cpu_utilisation
          expr: |
            label_replace(
              node_cpu_usage / on(cluster, node) node_cpu_total,
              "instance", "$1", "node", "(.*)"
            )

        # Node CPU allocatable (from K8s)
        - record: node_cpu_allocatable_total
          expr: |
            kube_node_status_allocatable{job="kube-state-metrics", resource="cpu"}

    - name: node-memory-metrics
      interval: 30s
      rules:
        # Node memory total - aggregate by node first, then add instance label
        - record: node_memory_total
          expr: |
            label_replace(
              sum without (instance) (
                sum by (cluster, node, instance) (node_memory_MemTotal_bytes{job="node-exporter"})
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node memory available
        - record: node_memory_available
          expr: |
            label_replace(
              sum without (instance) (
                sum by (cluster, node, instance) (node_memory_MemAvailable_bytes{job="node-exporter"})
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node memory usage (internal)
        - record: node_memory_usage
          expr: |
            label_replace(
              node_memory_total - on(cluster, node) node_memory_available,
              "instance", "$1", "node", "(.*)"
            )

        # Node memory used (alias for API compatibility)
        - record: node_memory_used
          expr: |
            node_memory_usage

        # Node memory utilisation (0-1 ratio)
        - record: node_memory_utilisation
          expr: |
            label_replace(
              node_memory_usage / on(cluster, node) node_memory_total,
              "instance", "$1", "node", "(.*)"
            )

        # Node memory allocatable (from K8s)
        - record: node_memory_allocatable_total
          expr: |
            kube_node_status_allocatable{job="kube-state-metrics", resource="memory"}

    - name: node-disk-metrics
      interval: 30s
      rules:
        # Node disk capacity (bytes) - root filesystem only
        - record: node_disk_size_capacity
          expr: |
            label_replace(
              sum by (cluster, node) (
                node_filesystem_size_bytes{job="node-exporter", mountpoint="/", fstype!~"tmpfs|fuse.*"}
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node disk available (bytes)
        - record: node_disk_size_available
          expr: |
            label_replace(
              sum by (cluster, node) (
                node_filesystem_avail_bytes{job="node-exporter", mountpoint="/", fstype!~"tmpfs|fuse.*"}
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node disk usage (bytes)
        - record: node_disk_size_usage
          expr: |
            label_replace(
              node_disk_size_capacity - on(cluster, node) node_disk_size_available,
              "instance", "$1", "node", "(.*)"
            )

        # Node disk inode total
        - record: node_disk_inode_total
          expr: |
            label_replace(
              sum by (cluster, node) (
                node_filesystem_files{job="node-exporter", mountpoint="/", fstype!~"tmpfs|fuse.*"}
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node disk inode usage
        - record: node_disk_inode_usage
          expr: |
            label_replace(
              sum by (cluster, node) (
                node_filesystem_files{job="node-exporter", mountpoint="/", fstype!~"tmpfs|fuse.*"}
                -
                node_filesystem_files_free{job="node-exporter", mountpoint="/", fstype!~"tmpfs|fuse.*"}
              ),
              "instance", "$1", "node", "(.*)"
            )

        # Node ephemeral storage allocatable
        - record: node_ephemeral_storage_allocatable_total
          expr: |
            kube_node_status_allocatable{job="kube-state-metrics", resource="ephemeral-storage"}

    - name: node-pod-metrics
      interval: 30s
      rules:
        # Node pod count
        - record: node_pod_count
          expr: |
            count by (cluster, node) (
              kube_pod_info{job="kube-state-metrics"}
            )

        # Node pod quota (max pods)
        - record: node_pod_quota
          expr: |
            kube_node_status_allocatable{job="kube-state-metrics", resource="pods"}

        # Node pod CPU requests total
        - record: node_pod_requests_cpu_total
          expr: |
            sum by (cluster, node) (
              kube_pod_container_resource_requests{job="kube-state-metrics", resource="cpu"}
              * on(cluster, namespace, pod) group_left(node)
              kube_pod_info{job="kube-state-metrics"}
            )

        # Node pod CPU limits total
        - record: node_pod_limits_cpu_total
          expr: |
            sum by (cluster, node) (
              kube_pod_container_resource_limits{job="kube-state-metrics", resource="cpu"}
              * on(cluster, namespace, pod) group_left(node)
              kube_pod_info{job="kube-state-metrics"}
            )

        # Node pod memory requests total
        - record: node_pod_requests_memory_total
          expr: |
            sum by (cluster, node) (
              kube_pod_container_resource_requests{job="kube-state-metrics", resource="memory"}
              * on(cluster, namespace, pod) group_left(node)
              kube_pod_info{job="kube-state-metrics"}
            )

        # Node pod memory limits total
        - record: node_pod_limits_memory_total
          expr: |
            sum by (cluster, node) (
              kube_pod_container_resource_limits{job="kube-state-metrics", resource="memory"}
              * on(cluster, namespace, pod) group_left(node)
              kube_pod_info{job="kube-state-metrics"}
            )

        # Node pod ephemeral storage requests total
        - record: node_pod_requests_ephemeral_storage_total
          expr: |
            sum by (cluster, node) (
              kube_pod_container_resource_requests{job="kube-state-metrics", resource="ephemeral-storage"}
              * on(cluster, namespace, pod) group_left(node)
              kube_pod_info{job="kube-state-metrics"}
            )
