{{- if and .Values.global.enabled .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-prometheus
    component: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-prometheus
  labels:
    app: edge-prometheus
    component: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-prometheus
  labels:
    app: edge-prometheus
    component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edge-prometheus
subjects:
- kind: ServiceAccount
  name: edge-prometheus
  namespace: {{ .Values.global.namespace }}
{{- end }}