{{- if and .Values.global.enabled .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: edge-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-prometheus
    component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: edge-prometheus
{{- end }}