{{- if and .Values.global.enabled .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: edge-prometheus
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-prometheus
  template:
    metadata:
      labels:
        app: edge-prometheus
        component: prometheus
    spec:
      serviceAccountName: edge-prometheus
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}
        imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
        ports:
        - containerPort: 9090
          name: web
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.console.libraries=/etc/prometheus/console_libraries"
        - "--web.console.templates=/etc/prometheus/consoles"
        - "--web.enable-lifecycle"
        - "--storage.tsdb.retention.time=15d"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-rules
          mountPath: /etc/prometheus/rules
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          {{- toYaml .Values.prometheus.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
      - name: prometheus-config
        configMap:
          name: edge-prometheus-config
      - name: prometheus-rules
        configMap:
          name: edge-prometheus-rules
      - name: prometheus-storage
        {{- if .Values.prometheus.persistence.enabled }}
        persistentVolumeClaim:
          claimName: edge-prometheus-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
{{- end }}