apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: workspace-recording-rules
  namespace: observability-system
  labels:
    prometheus: kube-prometheus
    role: recording-rules
    layer: workspace
    release: edge-monitoring
spec:
  groups:
    # ========================================================================
    # Workspace-level Aggregation Recording Rules
    # Purpose: Multi-tenant workspace resource metrics aggregation
    # Priority: P2
    # Dependencies: kube-state-metrics, cadvisor
    # Label Required: Namespaces must have label_theriseunion_io_workspace
    # ========================================================================
    - name: workspace-aggregation-rules
      interval: 30s
      rules:
        # =====================================================
        # CPU metrics (aggregated by workspace)
        # =====================================================

        - record: workspace:container_cpu_usage_seconds:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_cpu_usage_seconds_total{job="kubelet"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Memory metrics (aggregated by workspace)
        # =====================================================

        - record: workspace:container_memory_usage_bytes:sum
          expr: |
            sum by (cluster, workspace) (
              container_memory_usage_bytes{job="kubelet"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_memory_rss:sum
          expr: |
            sum by (cluster, workspace) (
              container_memory_rss{job="kubelet"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Pod count (aggregated by workspace)
        # =====================================================

        - record: workspace:kube_pod_info:count
          expr: |
            count by (cluster, workspace) (
              kube_pod_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Namespace count (aggregated by workspace)
        # =====================================================

        - record: workspace:kube_namespace:count
          expr: |
            count by (cluster, workspace) (
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Network metrics (aggregated by workspace)
        # =====================================================

        - record: workspace:container_network_receive_bytes:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_network_receive_bytes_total{job="kubelet", interface!="lo"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_network_transmit_bytes:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_network_transmit_bytes_total{job="kubelet", interface!="lo"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_network_receive_packets:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_network_receive_packets_total{job="kubelet", interface!="lo"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_network_transmit_packets:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_network_transmit_packets_total{job="kubelet", interface!="lo"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Disk I/O metrics (aggregated by workspace)
        # =====================================================

        - record: workspace:container_fs_reads:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_fs_reads_total{job="kubelet"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_fs_writes:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_fs_writes_total{job="kubelet"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_fs_reads_bytes:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_fs_reads_bytes_total{job="kubelet"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:container_fs_writes_bytes:sum_rate
          expr: |
            sum by (cluster, workspace) (
              irate(container_fs_writes_bytes_total{job="kubelet"}[5m])
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Resource Requests/Limits (aggregated by workspace)
        # =====================================================

        - record: workspace:kube_pod_container_resource_requests_memory:sum
          expr: |
            sum by (cluster, workspace) (
              kube_pod_container_resource_requests{job="kube-state-metrics", resource="memory"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:kube_pod_container_resource_limits_memory:sum
          expr: |
            sum by (cluster, workspace) (
              kube_pod_container_resource_limits{job="kube-state-metrics", resource="memory"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:kube_pod_container_resource_requests_cpu:sum
          expr: |
            sum by (cluster, workspace) (
              kube_pod_container_resource_requests{job="kube-state-metrics", resource="cpu"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        - record: workspace:kube_pod_container_resource_limits_cpu:sum
          expr: |
            sum by (cluster, workspace) (
              kube_pod_container_resource_limits{job="kube-state-metrics", resource="cpu"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # ========================================================================
        # Workspace Workload Count Rules
        # ========================================================================

        # Workspace deployment count
        - record: workspace:kube_deployment:count
          expr: |
            count by (cluster, workspace) (
              kube_deployment_spec_replicas{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace statefulset count
        - record: workspace:kube_statefulset:count
          expr: |
            count by (cluster, workspace) (
              kube_statefulset_replicas{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace daemonset count
        - record: workspace:kube_daemonset:count
          expr: |
            count by (cluster, workspace) (
              kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace job count
        - record: workspace:kube_job:count
          expr: |
            count by (cluster, workspace) (
              kube_job_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace cronjob count
        - record: workspace:kube_cronjob:count
          expr: |
            count by (cluster, workspace) (
              kube_cronjob_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace service count
        - record: workspace:kube_service:count
          expr: |
            count by (cluster, workspace) (
              kube_service_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace ingress count
        - record: workspace:kube_ingress:count
          expr: |
            count by (cluster, workspace) (
              kube_ingress_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # =====================================================
        # Resource utilization (calculated by workspace)
        # =====================================================

        - record: workspace:memory_utilization_percent
          expr: |
            (
              workspace:container_memory_usage_bytes:sum
              /
              workspace:kube_pod_container_resource_requests_memory:sum
            ) * 100

        - record: workspace:cpu_utilization_percent
          expr: |
            (
              workspace:container_cpu_usage_seconds:sum_rate
              /
              workspace:kube_pod_container_resource_requests_cpu:sum
            ) * 100

        # =====================================================
        # PVC/Storage metrics (aggregated by workspace)
        # =====================================================

        # Workspace PVC total count
        - record: workspace:kube_persistentvolumeclaim:count
          expr: |
            count by (cluster, workspace) (
              kube_persistentvolumeclaim_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace PVC bound count
        - record: workspace:kube_persistentvolumeclaim_bound:count
          expr: |
            count by (cluster, workspace) (
              kube_persistentvolumeclaim_status_phase{job="kube-state-metrics", phase="Bound"}
              * on(namespace, persistentvolumeclaim) group_left()
              kube_persistentvolumeclaim_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace PVC pending count
        - record: workspace:kube_persistentvolumeclaim_pending:count
          expr: |
            count by (cluster, workspace) (
              kube_persistentvolumeclaim_status_phase{job="kube-state-metrics", phase="Pending"}
              * on(namespace, persistentvolumeclaim) group_left()
              kube_persistentvolumeclaim_info{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace PVC total capacity (bytes)
        - record: workspace:kube_persistentvolumeclaim_capacity_bytes:sum
          expr: |
            sum by (cluster, workspace) (
              kube_persistentvolumeclaim_resource_requests_storage_bytes{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace bound PVC capacity (bytes) - used capacity
        - record: workspace:kube_persistentvolumeclaim_bound_capacity_bytes:sum
          expr: |
            sum by (cluster, workspace) (
              kube_persistentvolumeclaim_resource_requests_storage_bytes{job="kube-state-metrics"}
              * on(namespace, persistentvolumeclaim) group_left()
              kube_persistentvolumeclaim_status_phase{job="kube-state-metrics", phase="Bound"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace PV count (PVs bound to this workspace's PVCs)
        - record: workspace:kube_persistentvolume:count
          expr: |
            count by (cluster, workspace) (
              kube_persistentvolume_claim_ref{job="kube-state-metrics"}
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )

        # Workspace storage class count (unique storage classes used)
        - record: workspace:kube_storageclass:count
          expr: |
            count by (cluster, workspace) (
              group by (cluster, workspace, storageclass) (
                kube_persistentvolumeclaim_info{job="kube-state-metrics"}
                * on(namespace) group_left(workspace)
                label_replace(
                  kube_namespace_labels{label_theriseunion_io_workspace!=""},
                  "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
                )
              )
            )

        # Workspace PVC actual bytes used (from kubelet volume stats)
        - record: workspace:kube_persistentvolumeclaim_bytes_used:sum
          expr: |
            sum by (cluster, workspace) (
              kubelet_volume_stats_used_bytes
              * on(namespace) group_left(workspace)
              label_replace(
                kube_namespace_labels{label_theriseunion_io_workspace!=""},
                "workspace", "$1", "label_theriseunion_io_workspace", "(.*)"
              )
            )
