{{- if .Values.controller.enabled }}
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: edge-platform
    cluster.theriseunion.io/role: {{ .Values.global.mode }}
  annotations:
    # Mark as pre-installed to skip reconcile loop
    # Controller is already deployed as part of this Helm chart
    ext.theriseunion.io/pre-installed: "true"
    ext.theriseunion.io/skip-reconcile: "true"
    ext.theriseunion.io/installation-method: "helm-direct"
spec:
  enabled: true
  version: {{ .Chart.AppVersion }}
  # NOTE: No chart field - controller is pre-installed via Helm
  # This Component CR exists only for system recognition
{{- end }}