{{- if .Values.controller.enabled }}	
apiVersion: ext.theriseunion.io/v1alpha1	
kind: Component	
metadata:	
  name: edge-controller	
  namespace: {{ .Release.Namespace }}	
  labels:	
    {{- include "edge-controller.labels" . | nindent 4 }}	
    app.kubernetes.io/component: controller	
    app.kubernetes.io/part-of: edge-platform	
    cluster.theriseunion.io/role: {{ .Values.global.mode }}	
  annotations:	
    # Mark as pre-installed to skip reconcile loop in host cluster	
    # Controller is already deployed as part of this Helm chart	
    ext.theriseunion.io/pre-installed: "true"	
    ext.theriseunion.io/skip-reconcile: "true"	
    ext.theriseunion.io/installation-method: "helm-direct"	
spec:	
  enabled: true	
  version: {{ .Values.autoInstall.controller.version | default .Chart.Version }}
  chart:	
    name: edge-controller	
    namespace: {{ .Release.Namespace }}	
    releaseName: edge-platform	
    repository: http://chartmuseum.{{ .Release.Namespace }}.svc:{{ .Values.chartmuseum.service.port }}
  values:
    controller:
      {{- toYaml .Values.controller | nindent 6 }}
    chartmuseum:
      {{- toYaml .Values.chartmuseum | nindent 6 }}
    autoInstall:
      {{- toYaml .Values.autoInstall | nindent 6 }}
  # NOTE: Chart configuration is used by Cluster Controller when installing to member clusters	
  # Host cluster's controller is pre-installed via Helm (skip-reconcile: true)	
  # Member clusters use this configuration for automated controller installation	
{{- end }}	
