---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-system
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: iot-platform
---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: iot-apiserver
  namespace: edge-system
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: iot-apiserver
    app.kubernetes.io/part-of: iot-platform
    cluster.theriseunion.io/role: {{ .Values.global.mode }}
spec:
  enabled: false
  version: "0.1.0"
  chart:
    name: iot-apiserver
    namespace: edge-system
    releaseName: iot-apiserver
    repository: http://chartmuseum.{{ .Release.Namespace }}.svc:{{ .Values.chartmuseum.service.port }}
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: iot-controller
  namespace: edge-system
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: iot-controller
    app.kubernetes.io/part-of: iot-platform
    cluster.theriseunion.io/role: {{ .Values.global.mode }}
spec:
  enabled: false
  version: "0.1.0"
  chart:
    name: iot-controller
    namespace: edge-system
    releaseName: iot-controller
    repository: http://chartmuseum.{{ .Release.Namespace }}.svc:{{ .Values.chartmuseum.service.port }}
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
---
apiVersion: ext.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: yurt-iot-dock
  namespace: kube-system
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: yurt-iot-dock
    app.kubernetes.io/part-of: iot-platform
spec:
  enabled: false
  version: "1.6.0"
  chart:
    name: yurt-iot-dock
    namespace: kube-system
    releaseName: yurt-iot-dock
    repository: http://chartmuseum.{{ .Release.Namespace }}.svc:{{ .Values.chartmuseum.service.port }}